### ISSUE TITLE
The custom helpers like {jpmn-primary-definition} is not showing

### ISSUE THREAD

**Issue by Ryuuusuke** [arbyste/jp-mining-note#23]
all jpmn custom helpers is not showing on the card value. i did paste the code from this link https://arbyste.github.io/jp-mining-note-prerelease/setupyomitan/ one is on top and one on bottom. but they are still not showing

**Comment by FunLait** [comment]
any solution?

**Comment by Ryuuusuke** [comment]
> any solution?

you should copy and paste it. not choose it from drop down menu because its not showing the helpers
